source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'EasyTipView_Example', :exclusive => true do
  pod "EasyTipView", :path => "../"
end

target 'EasyTipView_Tests', :exclusive => true do
  pod "EasyTipView", :path => "../"

  
end
